from pydantic import BaseModel, Field


class CustomerData(BaseModel):

    gender: int = Field(..., description="Gender of the customer, 0 for female and 1 for male")
    Senior_Citizen: int = Field(..., description="Indicates if the customer is a senior citizen, 1 for yes, 0 for no")
    Is_Married: int = Field(..., description="Indicates if the customer is married, 1 for yes, 0 for no")
    Dependents: int = Field(..., description="Indicates if the customer has dependents, 1 for yes, 0 for no")
    tenure: int = Field(..., description="The number of months the customer has been with the company")
    Phone_Service: int = Field(..., description="Indicates if the customer has phone service, 1 for yes, 0 for no")
    Paperless_Billing: int = Field(..., description="Indicates if the customer uses paperless billing, 1 for yes, 0 for no")
    Monthly_Charges: float = Field(..., description="The monthly charges the customer pays")
    Total_Charges: float = Field(..., description="The total charges the customer has paid")
    Dual_No: int = Field(..., description="Indicates if the customer doesn't have a dual service, 1 for no, 0 for yes")
    Dual_No_phone_service: int = Field(..., description="Indicates if the customer has no phone service, 1 for no, 0 for yes")
    Dual_Yes: int = Field(..., description="Indicates if the customer has dual service, 1 for yes, 0 for no")
    Internet_Service_DSL: int = Field(..., description="Indicates if the customer has DSL internet service, 1 for yes, 0 for no")
    Internet_Service_Fiber_optic: int = Field(..., description="Indicates if the customer has fiber optic internet service, 1 for yes, 0 for no")
    Internet_Service_No: int = Field(..., description="Indicates if the customer has no internet service, 1 for no, 0 for yes")
    Online_Security_No: int = Field(..., description="Indicates if the customer has no online security, 1 for no, 0 for yes")
    Online_Security_No_internet_service: int = Field(..., description="Indicates if the customer has no internet service and no online security, 1 for no, 0 for yes")
    Online_Security_Yes: int = Field(..., description="Indicates if the customer has online security, 1 for yes, 0 for no")
    Online_Backup_No: int = Field(..., description="Indicates if the customer has no online backup, 1 for no, 0 for yes")
    Online_Backup_No_internet_service: int = Field(..., description="Indicates if the customer has no internet service and no online backup, 1 for no, 0 for yes")
    Online_Backup_Yes: int = Field(..., description="Indicates if the customer has online backup, 1 for yes, 0 for no")
    Device_Protection_No: int = Field(..., description="Indicates if the customer has no device protection, 1 for no, 0 for yes")
    Device_Protection_No_internet_service: int = Field(..., description="Indicates if the customer has no internet service and no device protection, 1 for no, 0 for yes")
    Device_Protection_Yes: int = Field(..., description="Indicates if the customer has device protection, 1 for yes, 0 for no")
    Tech_Support_No: int = Field(..., description="Indicates if the customer has no tech support, 1 for no, 0 for yes")
    Tech_Support_No_internet_service: int = Field(..., description="Indicates if the customer has no internet service and no tech support, 1 for no, 0 for yes")
    Tech_Support_Yes: int = Field(..., description="Indicates if the customer has tech support, 1 for yes, 0 for no")
    Streaming_TV_No: int = Field(..., description="Indicates if the customer has no streaming TV, 1 for no, 0 for yes")
    Streaming_TV_No_internet_service: int = Field(..., description="Indicates if the customer has no internet service and no streaming TV, 1 for no, 0 for yes")
    Streaming_TV_Yes: int = Field(..., description="Indicates if the customer has streaming TV, 1 for yes, 0 for no")
    Streaming_Movies_No: int = Field(..., description="Indicates if the customer has no streaming movies, 1 for no, 0 for yes")
    Streaming_Movies_No_internet_service: int = Field(..., description="Indicates if the customer has no internet service and no streaming movies, 1 for no, 0 for yes")
    Streaming_Movies_Yes: int = Field(..., description="Indicates if the customer has streaming movies, 1 for yes, 0 for no")
    Contract_Month_to_month: int = Field(..., description="Indicates if the customer has a month-to-month contract, 1 for yes, 0 for no")
    Contract_One_year: int = Field(..., description="Indicates if the customer has a one-year contract, 1 for yes, 0 for no")
    Contract_Two_year: int = Field(..., description="Indicates if the customer has a two-year contract, 1 for yes, 0 for no")
    Payment_Method_Bank_transfer_automatic: int = Field(..., description="Indicates if the customer pays by bank transfer (automatic), 1 for yes, 0 for no")
    Payment_Method_Credit_card_automatic: int = Field(..., description="Indicates if the customer pays by credit card (automatic), 1 for yes, 0 for no")
    Payment_Method_Electronic_check: int = Field(..., description="Indicates if the customer pays by electronic check, 1 for yes, 0 for no")
    Payment_Method_Mailed_check: int = Field(..., description="Indicates if the customer pays by mailed check, 1 for yes, 0 for no")
